const data = {
  days: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
  months: [
    'Jan',
    'Feb',
    'Mar',
    'Apr',
    'May',
    'Jun',
    'Jul',
    'Aug',
    'Sep',
    'Oct',
    'Nov',
    'Dec',
  ],
  WMO_codes: {
    0: 'clear',
    1: 'mainly clear',
    2: 'partially cloud',
    3: 'cloudy',
    45: 'fog',
    48: 'depositing rime fog',
    51: 'drizzle light',
    53: 'drizzle moderate',
    55: 'drizzle dense',
    56: 'freezing drizzle light',
    57: 'freezing drizzle dense',
    61: 'rain slight',
    63: 'rain moderate',
    65: 'rain heavy',
    66: 'freezing rain light',
    67: 'freezing rain heavy',
    71: 'snow slight',
    73: 'snow moderate',
    75: 'snow heavy',
    77: 'snow grains',
    80: 'shower slight',
    81: 'shower moderate',
    82: 'shower heavy',
    85: 'snow shower slight',
    86: 'snow shower heavy',
    95: 'thunderstorm slight',
    96: 'thunderstorm with slight hail',
    99: 'thunderstorm with heavy hail',
  },
};

export default data;
